# PART 1 - This is the main pipeline. It should be manually triggered from the GitHub Actions tab,
# while selecting the regions to provision the infrastructure.
name: Infra Terraform Main (part 1)

on:
  workflow_dispatch: # Trigger that allows to manually start the workflow from the GitHub Actions tab in the repository
  # It provides an interface where you can select specific inputs (such as regions) before running the workflow.
    inputs:
      us-east-1:
        description: 'N.Virginia (us-east-1)'
        required: false
        type: boolean
      eu-central-1:
        description: 'Stockholm (eu-central-1)'
        required: false
        type: boolean

jobs:
  us-east-1:
    if: ${{ github.event.inputs.us-east-1 == 'true' }}
    uses: ./.github/workflows/infra-provisioning-region.yaml
    with:
      region-code: us-east-1
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  eu-central-1:
    if: ${{ github.event.inputs.eu-central-1 == 'true' }}
    uses: ./.github/workflows/infra-provisioning-region.yaml
    with:
      region-code: eu-central-1
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN2 }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}