name: Polybot Microservice Deployment
# docker run --name my_polybot -p 8443:8443 -e REGION_NAME='us-east-1' -e DYNAMODB_TABLE='tf-shantalberkhof-predictions-dynamodb-table' shantalberkhof/my_polybot:v2
# Deploy the Polybot and the Yolo5 apps in their EC2 instances
on:
  push:
    paths:
      - 'polybot/**' # depends on paths inside yolo5
    branches:
      - main

env:
  EC2_PUBLIC_IP_POLYBOT1: 52.204.155.137 #needs to be changed in the if condition [ "$PUBLIC_IP" ==
  EC2_PUBLIC_IP_POLYBOT2: 18.207.175.130 #needs to be changed in the if condition [ "$PUBLIC_IP" ==
  POLYBOT_TARGET_GROUP_ARN1: arn:aws:elasticloadbalancing:us-east-1:019273956931:targetgroup/tf-shantalberkhof-polybot-tg/6cde070c0a349802 # Also change from tg of alb

jobs:
  BuildPolybot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push Polybot image to DockerHub
        run: |
          cd polybot
          docker login -u ${{ secrets.SHANTAL_DOCKERHUB_USERNAME }} -p ${{ secrets.SHANTAL_DOCKERHUB_PASSWORD }}
          IMAGE_NAME=${{ secrets.SHANTAL_DOCKERHUB_USERNAME }}/my_polybot:v2
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      
      - name: Set up SSH key
        run: |
          echo "${{ secrets.US_EAST_1_PRIVATE_KEY }}" > private_key1.pem
          chmod 600 private_key1.pem          
          echo "${{ secrets.US_EAST_1_PRIVATE_KEY }}" > private_key2.pem
          chmod 600 private_key2.pem
          

  DeployPolybot: # step 2
    name: Deploy to Polybot EC2 Instance
    runs-on: ubuntu-latest
    needs:
      - BuildPolybot
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION2 }}

    - name: Deploy to AWS EC2
      run: |
        IMAGE_NAME=${{ secrets.SHANTAL_DOCKERHUB_USERNAME }}/my_polybot:v2
        echo "AWS_REGION: $secrets.AWS_REGION2"

        echo "${{ secrets.US_EAST_1_PRIVATE_KEY }}" > private_key1.pem
        chmod 400 private_key1.pem          
        echo "${{ secrets.US_EAST_1_PRIVATE_KEY }}" > private_key2.pem
        chmod 400 private_key2.pem
        
        POLYBOT_INSTANCES=$(aws elbv2 describe-target-health --target-group-arn $POLYBOT_TARGET_GROUP_ARN1 --query 'TargetHealthDescriptions[*].Target.Id' --output text --region ${{ secrets.AWS_REGION2 }})
        echo "POLYBOT_INSTANCES: $POLYBOT_INSTANCES"
        
        for instance in $POLYBOT_INSTANCES; do
          INSTANCE_STATE=$(aws ec2 describe-instances --instance-ids $instance --query 'Reservations[0].Instances[0].State.Name' --output text --region ${{ secrets.AWS_REGION2 }})
                
          if [ "$INSTANCE_STATE" != "running" ]; then
            echo "Instance $instance is $INSTANCE_STATE. Starting the instance..."
            aws ec2 start-instances --instance-ids $instance --region ${{ secrets.AWS_REGION2 }}
        
            echo "Waiting for instance $instance to be in running state..."
            aws ec2 wait instance-running --instance-ids $instance --region ${{ secrets.AWS_REGION2 }}
          fi
        
          INSTANCE_INFO=$(aws ec2 describe-instances --instance-ids $instance --query 'Reservations[0].Instances[0]' --output json --region ${{ secrets.AWS_REGION2 }})
          echo "Instance Info: $INSTANCE_INFO"
          PUBLIC_IP=$(echo $INSTANCE_INFO | jq -r '.PublicIpAddress')
        
          if [ "$PUBLIC_IP" == "null" ] || [ -z "$PUBLIC_IP" ]; then
            echo "No public IP found for instance $instance"
            continue
          fi
         
          CurKey=private_key1.pem
        
          if [ "$PUBLIC_IP" == "18.207.175.130" ]; then
            CurKey=private_key2.pem
          fi
        
          echo "Instance ID: $instance, Public IP: $PUBLIC_IP, CurKey: $CurKey"              
          
          # Retry SSH connection up to 5 times with a delay
          for attempt in {1..5}; do
            echo "Attempt $attempt to connect to $PUBLIC_IP"
            if ssh -o StrictHostKeyChecking=no -i $CurKey ubuntu@$PUBLIC_IP "echo 'SSH connection successful'"; then
        
              echo "SSH connection successful to $PUBLIC_IP"

              ssh -o StrictHostKeyChecking=no -i $CurKey ubuntu@$PUBLIC_IP "sudo docker stop my_polybot || true"
              ssh -o StrictHostKeyChecking=no -i $CurKey ubuntu@$PUBLIC_IP "sudo docker rm my_polybot || true"
        
              ssh -o StrictHostKeyChecking=no -i $CurKey ubuntu@$PUBLIC_IP "sudo docker pull $IMAGE_NAME"
              ssh -o StrictHostKeyChecking=no -i $CurKey ubuntu@$PUBLIC_IP "sudo docker run -d --name my_polybot -p 8443:8443 -e REGION_NAME='us-east-1' -e DYNAMODB_TABLE='tf-shantalberkhof-predictions-dynamodb-table' -e TELEGRAM_APP_URL='6889860814:AAGJU6KNTn0rmNx17XiI49IenE_642rvAnQ' $IMAGE_NAME"
              break
            else
              echo "SSH connection to $PUBLIC_IP failed. Retrying in 10 seconds..."
              sleep 10
            fi
          done
        done
      env:
        AWS_REGION: ${{ secrets.AWS_REGION2 }}
