# Commit and push this and: region-us-east-1.tfvars OR region-eu-central-1.tfvars
# Export YOLO5_IMAGE=shantalberkhof/my_yolo5:v2 # was :latest

name: Yolo5 Infra Terraform Region (part 2)

on:
  workflow_call:
    inputs:
      region-code:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      PRIVATE_KEY:
        required: true

jobs:

  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push Yolo image to DockerHub
        run: |
          cd yolo5
          docker login -u ${{ secrets.SHANTAL_DOCKERHUB_USERNAME }} -p ${{ secrets.SHANTAL_DOCKERHUB_PASSWORD }} --password-stdin
          IMAGE_NAME=${{ secrets.SHANTAL_DOCKERHUB_USERNAME }}/my_yolo5:v2
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME   

#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v2
#      Allows running aws commands
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Get Yolo5 EC2's IP
        env:
          AWS_DEFAULT_REGION: ${{ inputs.region-code }}
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

       # Gets instances id from yolo5 ec2 by their tags
          INSTANCES_IDS=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=shantalberkhof-yolo5-ec2" \
            --query 'Reservations[*].Instances[*].InstanceId' --output text)

          for instance_id in $INSTANCES_IDS;
          do
            state=$(aws ec2 describe-instances --instance-ids $instance_id --query 'Reservations[*].Instances[*].State.Name' --output text)
            echo "The instance - $instance_id is in state - $state"
               
            if [ "$state" = "terminated" ]; then
              echo "Instance terminated, skipping."
            elif [ "$state" = "stopped" ]; then
              echo "Starting instance $instance_id..."
              aws ec2 start-instances --instance-ids $instance_id
              aws ec2 wait instance-running --instance-ids $instance_id
            else
              echo "Instance $instance_id already running."
            fi
          done

          # Gets public ip from yolo5 ec2 by their tags (Gets only from running EC2s).
          YOLO5_SERVERS_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=shantalberkhof-yolo5-ec2" \
            --query 'Reservations[*].Instances[*].PublicIpAddress' --output text | grep -v None)
               
          echo "The IPs of running Yolo5 EC2's are- $YOLO5_SERVERS_IP"

#          echo "YOLO5_SERVERS_IP<<EOF" >> "$GITHUB_ENV"
#          echo "$YOLO5_SERVERS_IP" >> "$GITHUB_ENV"
          echo "YOLO5_SERVERS_IP=$YOLO5_SERVERS_IP" >> "$GITHUB_ENV" # NEW CORRECTION
          #echo EOF >> "$GITHUB_ENV"

      - name: Deploy YOLOv5 to EC2 in specific region
        env:
          AWS_DEFAULT_REGION: ${{ inputs.region-code }}
          PRIVATE_KEY: ${{ secrets.US_EAST_1_PRIVATE_KEY }}
        run: |
          cd tf
          # Gets from tfvars file the owner name
          OWNER=$(grep owner region.us-east-1.tfvars | grep -o '".*"' | sed 's/"//g')
          cd ..

          # create .env file with needed values.
          echo "BUCKET_NAME=tf-$OWNER-images-bucket-us-east-1
          SQS_QUEUE_NAME=tf-$OWNER-project-queue
          REGION_NAME=us-east-1
          DYNAMODB_TABLE=tf-$OWNER-predictions-dynamodb-table
          ALB_URL=$OWNER-polybot-us-east-1.int-devops.click:8443" > .env

          # Gets from env only the IPs
          YOLO5_SERVERS_IP=${YOLO5_SERVERS_IP#*:}
          echo "The IPs of running Yolo5 EC2's are- $YOLO5_SERVERS_IP"

          export YOLO5_IMAGE=shantalberkhof/yolo5-aws-project:v2
          echo "yolo5 image - $YOLO5_IMAGE"

          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

          for SERVER_IP in $YOLO5_SERVERS_IP; do
            # Copies .env file to ec2
            scp -o StrictHostKeyChecking=no -i private_key .env ubuntu@$SERVER_IP:/home/ubuntu/
            # Connects to ec2
            ssh -o StrictHostKeyChecking=no -i private_key ubuntu@$SERVER_IP <<EOF
              YOLO5_IMAGE=shantalberkhof/my_yolo5:v2 # was latest
              docker stop my_yolo5 || true && docker rm my_yolo5 || true
              docker run -d --restart always --env-file /home/ubuntu/.env --name my_yolo5 \$YOLO5_IMAGE
              docker ps | grep my_yolo5 || exit 1
          EOF
          done
