name: Yolo5 Microservice Deployment

on:
  push:
    paths:
      - 'yolo5/**'
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.SHANTAL_DOCKERHUB_USERNAME }}
          password: ${{ secrets.SHANTAL_DOCKERHUB_PASSWORD }}

      - name: Build and push image
        run: |
          cd yolo5
          docker build -t shantalberkhof/my_yolo5:v1 .
          docker push shantalberkhof/my_yolo5:v1
          # TODO your implementation here....          

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2
      - name: Deploy new version
        run: |         
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY_PATH }} ubuntu@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
            docker pull shantalberkhof/my_yolo5:v1
            docker stop my_yolo5 || true
            docker rm my_yolo5 || true
            docker run -d -p 8080:80 --name my_yolo5 shantalberkhof/my_yolo5:v1
          EOF     
